#spring:
#  datasource:
#    hikari:
#      jdbc-url: jdbc:mysql://springboot-db.cd9b2fhfvoml.ap-northeast-2.rds.amazonaws.com:3306/myspringboot
#      username: sparta112
#      password: sparta112
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        show_sql: true
#  jackson:
#    serialization:
#      fail-on-empty-beans: false
#
#server:
#  servlet:
#    encoding:
#      charset: utf-8
#      enabled: true
#      force: true
#
#jwt:
#  secret: 4oCYc3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LWhhbmdoYWUtYXNzaWdubWVudC1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3Qtc2VjcmV0LWtleeKAmQo=
#
#cloud:
#  aws:
#    credentials:
#      access-key: AKIAVAVNFEEHFLS647PC
#      secret-key: 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
#    s3: #????
#      bucket: bucket=myspringboot--bucket
#    region: #S3 ??
#      static: ap-northeast-2
#    stack:
#      auto: false
## multipartFile ?? ???? ??
#spring:
#  servlet:
#    multipart:
#      max-file-size: 10MB
#      max-request-size: 10MB